Побудувати матрицю, складену біномними коефіцієнтами, та знайти обернену. Чи є матриця оберненою сама до себе?

In [ ]:
import numpy as np
import math as mt

def matrix(n):
    mat = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            if i >= j:
                mat[i, j] = mt.comb(i, j) * ((-1)**j)
    print(f'Матриця:\n{mat}')
    print(f'Обернена матриця:\n{mat}')
matrix(5)

7. Написати функцію обчислення лінійного індексу елемента багатовимірного масиву за його
багатовимірним індексом у багатовимірному масиві та розмірами у випадку використання F-порядку.

In [ ]:
def indexC(mat, i, j):
    cols=mat.shape
    cind=i*cols+j
    
    return cind

17. Побудувати матрицю випадкових дійсних чисел. Для отриманої матриці знайти:
а) середнє арифметичне;
б) найбільше значення;
в) медіану.
Наведені статистики знайти:
1) для матриці в цілому;
2) для кожного стовпця матриці;
3) для кожного рядка.

In [ ]:
import random
import numpy as np

mat = np.zeros((5, 5))
for i in range(5):
    for j in range(5):
        mat[i, j] = random.random()
print(mat)
print(f'Max val: {mat.max()}')
print(f'Median: {np.median(mat)}')
print(f'Medium val: {mat.mean()}')

19. Побудувати матрицю випадкових цілих чисел з проміжку [-100; 100]. Для отриманої матриці знайти
а) кількість її додатних елементів;
б) кількість її непарних елементів.

In [19]:
import numpy as np
import random

mat = np.zeros((3, 3), dtype=int)
countPlus = 0
countNotDiv2 = 0
for i in range(3):
    for j in range(3):
        mat[i, j] = random.randint(-100, 100)
        if mat[i, j] > 0:
            countPlus += 1
        if mat[i, j] % 2 == 1:
            countNotDiv2 +=1
print(mat)
print(countPlus, countNotDiv2)

[[-50 -57  53]
 [ 79 -86  10]
 [ 25 -10  33]]
5 5
