Написати код, який виконує такі дії:
1. Імпортувати модуль numpy під іменем np
2. Створити цілі змінні n та m, що будуть задавати розміри майбутньої матриці.
3. Створити порожню матрицю a цілих чисел, і заповнити її нульовими значеннями.
4. Створити цілі зміні left_lim, right_lim які будуть задавати верхній та нижній поріг заповнення матриці
5. Заповнити матрицю випадковими цілими числами в діапазоні з пункту 4 
Для цього , з модуля random імпортувати функцію randint, яка повертає випадкове ціле в заданому діапазоні, наприклад: randint(3, 5) поверне ціле від 3 до 5 включно.
6.У циклі обійти всі елементи матриці та встановити значення. Має бути два цикли: зовнішній цикл по рядках, внутрішній по стовпчиках (чи навпаки).
7.  Вивести отриману матрицю
*8. Створити функцію, яка на вхід отримує матрицю, та для кожного її елементу ставить у відповідність квадрат його величини. Реалізувати функцію за допомогою проходу по всім елементам послідовності, а також створити ще одну функцію з таким самим результатом, але за допомогою вбудованих операцій над матрицями( додавання, множення або інші)
*9. Викликати обидві функції(пункт 8) на однакових даних, та переконатись що результат ідентичний.

In [35]:
import numpy as np
from random import randint

In [36]:
n = 3
m = 3

In [37]:
a = np.zeros((n,m),dtype=int)
print(a)
print(a.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64


In [38]:
left_lim = 0
right_lim = 20

In [39]:
for i in range(len(a)):
    for j in range(len(a[i])):
        a[i,j] = randint(left_lim, right_lim)
print(a)

[[20 16 16]
 [11 14 11]
 [ 0  6 19]]


In [40]:
def matSqured(mat):
    c = mat.copy()
    for i in range(len(c)):
        for j in range(len(c[i])):
            c[i,j] **= 2
    return c

def matSqured2(mat):
    s = mat.copy()
    return s*s
print(matSqured(a))
print(matSqured2(a))

[[400 256 256]
 [121 196 121]
 [  0  36 361]]
[[400 256 256]
 [121 196 121]
 [  0  36 361]]
